version: '3.9'

services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_ROOT}/sabnzbd:/config
      - ${LOG_ROOT}/sabnzbd:/config/logs
      - ${NZB_DOWNLOAD_ROOT}:/downloads
      - ${NZB_DOWNLOAD_TEMP}:/incomplete-downloads
      - ${NZB_DOWNLOAD_ROOT}:/config/Downloads/complete
      - ${NZB_DOWNLOAD_TEMP}:/config/Downloads/incomplete
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.sabnzbd.rule=(Host(`${HOSTNAME}`) && PathPrefix(`/sabnzbd`) || PathPrefix(`/sabnzbd`))
      - traefik.http.routers.sabnzbd.tls=true
      - traefik.http.routers.sabnzbd.tls.certresolver=myresolver
      - traefik.http.services.sabnzbd.loadbalancer.server.port=8080
      - homepage.group=Download
      - homepage.name=Sabnzbd
      - homepage.icon=sabnzbd.png
      - homepage.href=/sabnzbd
      - homepage.description=Usenet
      - homepage.weight=6
      - homepage.widget.type=sabnzbd
      - homepage.widget.url=http://sabnzbd:8080
      - homepage.widget.key=${SABNZBD_API_KEY}
      - com.centurylinklabs.watchtower.enable=true
