version: "3.9"
services:
  tdarr:
    image: ghcr.io/haveagitgat/tdarr:latest
    container_name: tdarr
    restart: unless-stopped
    volumes:
      - ${CONFIG_ROOT}/tdarr_server/server:/app/server
      - ${CONFIG_ROOT}/tdarr_server/configs:/app/configs
      - ${LOG_ROOT}/tdarr_server:/app/logs
      - ${DATA_ROOT}:/data
      - ${TDARR_CACHE}:/temp
    ports:
      - "8265:8265"
      - "8266:8266"
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
      - UMASK_SET=002
      - serverPort=${TDARR_SERVER_PORT}
      - webUIPort=8265
      - internalNode=false
      - inContainer=true
    labels:
      - traefik.enable=true
      - traefik.http.routers.tdarr.rule=(PathPrefix(`/tdarr`))
      - traefik.http.routers.tdarr.tls=true
      - traefik.http.routers.tdarr.tls.certresolver=myresolver
      - traefik.http.services.tdarr.loadbalancer.server.port=8265
      - traefik.http.routers.tdarr.middlewares=tdarr-strip-slash,tdarr-stripprefix
      - traefik.http.middlewares.tdarr-stripprefix.stripPrefix.prefixes=/tdarr
      - traefik.http.middlewares.tdarr-strip-slash.redirectregex.regex=(^.*\/tdarr$$)
      - traefik.http.middlewares.tdarr-strip-slash.redirectregex.replacement=$$1/
      - traefik.http.middlewares.tdarr-strip-slash.redirectregex.permanent=false
      - homepage.group=Helpers
      - homepage.name=Tdarr
      - homepage.icon=tdarr.png
      - homepage.href=/tdarr/
      - homepage.description=Tdarr Server
      - homepage.weight=5
      - homepage.widget.type=tdarr
      - homepage.widget.url=http://tdarr:8265
